-- ============================================================
--  GEAMH HRIS - Casual Employees Seed Data
--  Sources: geamh-mab-dialysis casual listing (GEAMH)
--           list casual employees per position (KPFH)
--  Run this in phpMyAdmin > geamh_hris database > SQL tab
--  Uses INSERT IGNORE to skip duplicates on employee_no
-- ============================================================

USE geamh_hris;

INSERT IGNORE INTO employees
  (employee_no, last_name, first_name, middle_name, position, department, employment_status, active)
VALUES
-- ── GEAMH CASUAL (geamh-mab-dialysis listing) ──────────────────────────────
('GEAMH-C001','Agrimano','Rheanbelle','C.','Administrative Aide III','Nursing','Casual',1),
('GEAMH-C002','Alcazar','Lesly Ann','P.','Nurse I','Nursing','Casual',1),
('GEAMH-C003','Almanzor','Kristel Jane','V.','Nurse I','Nursing','Casual',1),
('GEAMH-C004','Alvarez','Mariane Xyril','F.','Administrative Aide III','Nursing','Casual',1),
('GEAMH-C005','Amurao','Chelsea','B.','Nurse I','Nursing','Casual',1),
('GEAMH-C006','Apostol','April Mae','','Nurse I','Nursing','Casual',1),
('GEAMH-C007','Aquiatan','Grace','A.','Nurse I','Nursing','Casual',1),
('GEAMH-C008','Arroyo','Mercy','C.','Social Welfare Assistant','Nursing','Casual',1),
('GEAMH-C009','Asas','Lee Leigh','T.','Nurse I','Nursing','Casual',1),
('GEAMH-C010','Asas','Naira Jane','V.','Nurse I','Nursing','Casual',1),
('GEAMH-C011','Atas','Noel','M.','Administrative Aide I','Nursing','Casual',1),
('GEAMH-C012','Atijera','Edelyne Mae','B.','Nurse I','Nursing','Casual',1),
('GEAMH-C013','Aure','Chrystal Joice','B.','Nurse I','Nursing','Casual',1),
('GEAMH-C014','Austria','Airish','M.','Nurse I','Nursing','Casual',1),
('GEAMH-C015','Ayo','Marilyn','A.','Administrative Aide III','Nursing','Casual',1),
('GEAMH-C016','Azarcon','Madelaine','V.','Pharmacist I','Pharmacy','Casual',1),
('GEAMH-C017','Bacsal','Feena','D.','Nurse I','Nursing','Casual',1),
('GEAMH-C018','Badian','Jaycelle','S.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C019','Baladiang','Harold Jason','D.','Nurse I','Nursing','Casual',1),
('GEAMH-C020','Bale','Lylamie','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C021','Balita','Edwin','S.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C022','Bay','Michael','L.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C023','Bersamina','Aebrille','C.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C024','Billones','Lady Anne','P.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C025','Bondal','Arvin','S.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C026','Buendia','Pamela','T.','Nurse I','Nursing','Casual',1),
('GEAMH-C027','Bueno','Marion Joy','A.','Nurse I','Nursing','Casual',1),
('GEAMH-C028','Buhain','Madonna','T.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C029','Buhay','Hazel Ann','D.','Nurse I','Nursing','Casual',1),
('GEAMH-C030','Buid','Ronnel','V.','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C031','Caacbay','Rodelynne','E.','Pharmacist I','Pharmacy','Casual',1),
('GEAMH-C032','Camarinta','Caryl','C.','Nurse I','Nursing','Casual',1),
('GEAMH-C033','Cayanan','Abigail','E.','Nurse I','Nursing','Casual',1),
('GEAMH-C034','Cayao','Ella Marie','M.','Nurse I','Nursing','Casual',1),
('GEAMH-C035','Cayao','Emerson','C.','Nurse I','Nursing','Casual',1),
('GEAMH-C036','Caymo','Myranhel','B.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C037','Cervantes','Julienne Mirano','','Pharmacist I','Pharmacy','Casual',1),
('GEAMH-C038','Comia','Irish','A.','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C039','Corral','Jennylyn','V.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C040','Costa','Marilyn','C.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C041','Costelo','Reggie','C.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C042','Cresido','Veronica','P.','Nurse I','Nursing','Casual',1),
('GEAMH-C043','Cresino','Mark Jay','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C044','Crizaldo','Jonathan','C.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C045','Cubillo','Ma. Fatima','P.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C046','Cueno','Haven Kyle','C.','Nurse I','Nursing','Casual',1),
('GEAMH-C047','Dabanda','Rosemarie','R.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C048','Dalisay','Chris Lester','C.','Nurse I','Nursing','Casual',1),
('GEAMH-C049','Dalisay','Fatima Joy','P.','Nurse I','Nursing','Casual',1),
('GEAMH-C050','De Borja','Verna Fe','M.','Administrative Aide III','Administrative','Casual',1)
,('GEAMH-C051','De Castro','ShaiNa','T.','Nurse I','Nursing','Casual',1),
('GEAMH-C052','De Castro','ShaiRa','T.','Nurse I','Nursing','Casual',1),
('GEAMH-C053','De Lara','Mary Christine','C.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C054','De San Jose','Harlene','H.','Nurse I','Nursing','Casual',1),
('GEAMH-C055','De Vera','Joylyn','Z.','Nurse I','Nursing','Casual',1),
('GEAMH-C056','Decillo','Nida','J.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C057','Dela Cruz','Maida','','Nurse I','Nursing','Casual',1),
('GEAMH-C058','Dela Cruz','Yvette','R.','Nurse I','Nursing','Casual',1),
('GEAMH-C059','Dela Pena','Wenilyn','M.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C060','Delfin','Norman Vincent','R.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C061','Delos Reyes','Kathy','M.','Nurse I','Nursing','Casual',1),
('GEAMH-C062','Delovino','Nadine','H.','Nurse I','Nursing','Casual',1),
('GEAMH-C063','Denosta','Genilyn','P.','Nurse I','Nursing','Casual',1),
('GEAMH-C064','Dilig','Imelda','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C065','Dimapilis','Jake Kirby','L.','Pharmacist I','Pharmacy','Casual',1),
('GEAMH-C066','Dinglasan','Maribel','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C067','Dolz','Camille','D.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C068','Dumagat','Vernadeth','B.','Nurse I','Nursing','Casual',1),
('GEAMH-C069','Elicierto','Joan Michelle','L.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C070','Eseque','Princess Joy','R.','Nurse I','Nursing','Casual',1),
('GEAMH-C071','Espiritu','Rowena','F.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C072','Estacio','Jennifer Mae Hayes','','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C073','Fabre','Elaine','C.','Nurse I','Nursing','Casual',1),
('GEAMH-C074','Fabro','Ma. Jumeline','A.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C075','Fello','Rencel Roan','C.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C076','Feranil','Helbert','L.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C077','Flores','Celerina','T.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C078','Flores','Eidle Wise','B.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C079','Flores','Gigi','F.','Nurse I','Nursing','Casual',1),
('GEAMH-C080','Flores','Maria Patrisha Nicole','','Nurse I','Nursing','Casual',1),
('GEAMH-C081','Flores','Reynaldo','B.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C082','Fuaso','Joelee Larise Allen','L.','Nurse I','Nursing','Casual',1),
('GEAMH-C083','Gallego','Joan Heyniel','A.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C084','Garcia','Lyra Gemma','M.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C085','Golfo','Janelle','P.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C086','Gonzales','Arjay','Y.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C087','Gonzales','Daniel','P.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C088','Gonzales','Lloyd','E.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C089','Gonzales','Tonette Bray','','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C090','Guinto','Elvira','V.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C091','Hernandez','Angelo Jehn Eidref','S.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C092','Hernandez','Donato','Q.','Nurse I','Nursing','Casual',1),
('GEAMH-C093','Hernandez','Gabriel Kein','G.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C094','Hernandez','Vanessa','B.','Nurse I','Nursing','Casual',1),
('GEAMH-C095','Herrera','Ethel Joy','G.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C096','Honrada','Rosafe','G.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C097','Janolo','Russel Christian','E.','Nurse I','Nursing','Casual',1),
('GEAMH-C098','Jeciel','Daniel Vhince','M.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C099','Junsay','Maria Menchie Loria','','Nurse I','Nursing','Casual',1),
('GEAMH-C100','Juson','Agnes Sanico','','Nursing Attendant I','Nursing','Casual',1)
,('GEAMH-C101','Lascano','Elrish Laine','G.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C102','Laure','Romeo Jr.','P.','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C103','Lavador','Edrize','A.','Social Welfare Assistant','Social Work','Casual',1),
('GEAMH-C104','Levita','Hariett Marian Ros','T.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C105','Limbo','Edwin','P.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C106','Lizardo','Jessica','B.','Nurse I','Nursing','Casual',1),
('GEAMH-C107','Macantan','Catherine','B.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C108','Maderazo','Kim Gellyssa','D.','Nurse I','Nursing','Casual',1),
('GEAMH-C109','Magayam','Cleo Mae','B.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C110','Malabanan','Jake Rojan','E.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C111','Mendoza','Elionor Vargas','','Nurse I','Nursing','Casual',1),
('GEAMH-C112','Merca','Menerissa','R.','Nurse I','Nursing','Casual',1),
('GEAMH-C113','Mercado','Marnie Marie','B.','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C114','Moico','Princess May','P.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C115','Mojica','Michelle','A.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C116','Monton','Patrick','L.','Nurse I','Nursing','Casual',1),
('GEAMH-C117','Morada','Rowena Irish','A.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C118','Murata','Rolf Nico','M.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C119','Nicomedes','Ma. Cristina','M.','Nurse I','Nursing','Casual',1),
('GEAMH-C120','Niviar','Mark Carlo','A.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C121','Nocidal','Henry','V.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C122','Noel','Joanna Kristin','A.','Nurse I','Nursing','Casual',1),
('GEAMH-C123','Nuestro','Princess','R.','Social Welfare Assistant','Social Work','Casual',1),
('GEAMH-C124','Nueva','Jesusa','S.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C125','Nueva','Kimberly Rose','B.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C126','Nueva','Tyrone','P.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C127','Pabalate','Digna','P.','Nurse I','Nursing','Casual',1),
('GEAMH-C128','Pacete','Cay Enriquez','','Pharmacist I','Pharmacy','Casual',1),
('GEAMH-C129','Palmario','Prescila','G.','Administrative Aide IV','Administrative','Casual',1),
('GEAMH-C130','Panganiban','Alfie','I.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C131','Pejana','Roxanne','R.','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C132','Pendon','Alvin','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C133','Penus','Maeka Penalba','','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C134','Perena','Gina','E.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C135','Perena','Karen Louise','M.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C136','Perin','Emma','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C137','Pinazo','Katelyne','S.','Radiologic Technologist I','Radiology','Casual',1),
('GEAMH-C138','Poblete','Sheila Marie','P.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C139','Puedan','Jenivic','E.','Nurse I','Nursing','Casual',1),
('GEAMH-C140','Punilas','Maria Beatriz','E.','Nurse I','Nursing','Casual',1),
('GEAMH-C141','Quijano','Renante','L.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C142','Quirap','Marvin','S.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C143','Rabanzo','Abegail','P.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C144','Ramirez','Devy','','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C145','Ramos','Rosita','D.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C146','Reyes','Clariza','B.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C147','Reyes','Irish Mae Nabata','','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C148','Reyes','Maria Rhea','A.','Nurse I','Nursing','Casual',1),
('GEAMH-C149','Riego De Dios','Triccia Anne','M.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C150','Rizo','Eddie Jr.','M.','Administrative Aide I','Administrative','Casual',1)
,('GEAMH-C151','Rodil','Bernard','A.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C152','Rodil','Nicca','I.','Nurse I','Nursing','Casual',1),
('GEAMH-C153','Rom','Merly','C.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C154','Romanes','Maybeljoy','C.','Nurse I','Nursing','Casual',1),
('GEAMH-C155','Salas','Ryza','G.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C156','Salgado','Jay','R.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C157','Saliedo','Richard','S.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C158','Salvio','Melissa Joy','B.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C159','Sanchez','Jaypee','H.','Nurse I','Nursing','Casual',1),
('GEAMH-C160','Santander','Ace','','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C161','Santos','Marjorie','G.','Nurse I','Nursing','Casual',1),
('GEAMH-C162','Secreto','Vilma','G.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C163','Serrano','Ereca Jayomana','','Nurse I','Nursing','Casual',1),
('GEAMH-C164','Sibucao','Ma. Victoria','A.','Nurse I','Nursing','Casual',1),
('GEAMH-C165','Sierra','Ara Mina','M.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C166','Signo','Lorie Antonette','D.','Nurse I','Nursing','Casual',1),
('GEAMH-C167','Simbahan','Lovely Lyl-Ann Sierra','','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C168','Socito','Kristel','E.','Nursing Attendant I','Nursing','Casual',1),
('GEAMH-C169','Sol','Christian Rafael','S.','Physical Therapist I','Rehabilitation','Casual',1),
('GEAMH-C170','Solis','Mylin','G.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C171','Tafalla','Jess Jason','P.','Nurse I','Nursing','Casual',1),
('GEAMH-C172','Tagustos','Carizza Krisell','B.','Medical Technologist I','Laboratory','Casual',1),
('GEAMH-C173','Tuazon','Emma','C.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C174','Valerio','Christianne Jane','L.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C175','Viadoy','Concepcion','A.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C176','Vicedo','Flordeliza','A.','Administrative Aide III','Administrative','Casual',1),
('GEAMH-C177','Vicedo','Jhanine','P.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C178','Vidallo','Upracio Jr.','A.','Administrative Aide I','Administrative','Casual',1),
('GEAMH-C179','Villanueva','Ma Criselda','D.','Nurse I','Nursing','Casual',1),
('GEAMH-C180','Volante','Mary Avigail','A.','Administrative Aide I','Administrative','Casual',1),
-- MAB & Dialysis Extension
('GEAMH-C181','Aure','Kevin','R.','Nurse I','Medical Arts Building','Casual',1),
('GEAMH-C182','Acak','Rodelin Cabalfin','','Administrative Aide I','Medical Arts Building','Casual',1),
('GEAMH-C183','Gatdula','Gat Rolliezen','','Nurse I','Dialysis Extension Clinic','Casual',1),
('GEAMH-C184','Rollan','Darvin','','Administrative Aide I','Dialysis Extension Clinic','Casual',1)
-- ── KPFH CASUAL (list per position) ────────────────────────────────────────
,('KPFH-C001','Amparo','Rhoy','V.','Nurse I','Nursing','Casual',1),
('KPFH-C002','Amutan','Eunicaella','A.','Nurse I','Nursing','Casual',1),
('KPFH-C003','And','Daisy','Y.','Nurse I','Nursing','Casual',1),
('KPFH-C004','Anglo','Ian Rodel','B.','Nurse I','Nursing','Casual',1),
('KPFH-C005','Anglo','Joshua Christine','M.','Nurse I','Nursing','Casual',1),
('KPFH-C006','Asas','Mark Anthony','V.','Nurse I','Nursing','Casual',1),
('KPFH-C007','Baldoza','Jules Ashley','S.','Nurse I','Nursing','Casual',1),
('KPFH-C008','Bansales','Ma. Carmela','V.','Nurse I','Nursing','Casual',1),
('KPFH-C009','Belardo','Ailene Grace','F.','Nurse I','Nursing','Casual',1),
('KPFH-C010','Belleza','Maria Eden','C.','Nurse I','Nursing','Casual',1),
('KPFH-C011','Buale','Hazel','A.','Nurse I','Nursing','Casual',1),
('KPFH-C012','Bulatao','Sharon','B.','Nurse I','Nursing','Casual',1),
('KPFH-C013','Cabintoy','Clark','P.','Nurse I','Nursing','Casual',1),
('KPFH-C014','Cabrera','Andrew Louie','G.','Nurse I','Nursing','Casual',1),
('KPFH-C015','Calimutan','Girby Joe','C.','Nurse I','Nursing','Casual',1),
('KPFH-C016','Causaren','Jennilyn','C.','Nurse I','Nursing','Casual',1),
('KPFH-C017','Costa','Honeylyn','C.','Nurse I','Nursing','Casual',1),
('KPFH-C018','David','Rachel Anne','A.','Nurse I','Nursing','Casual',1),
('KPFH-C019','Denauto','Christine Angela','C.','Nurse I','Nursing','Casual',1),
('KPFH-C020','Ebojo','Stephanie Claire','B.','Nurse I','Nursing','Casual',1),
('KPFH-C021','Ersando','Diane Michelle','D.','Nurse I','Nursing','Casual',1),
('KPFH-C022','Escalante','Karen','P.','Nurse I','Nursing','Casual',1),
('KPFH-C023','Escano','Kith','E.','Nurse I','Nursing','Casual',1),
('KPFH-C024','Escober','Allianna Marie','P.','Nurse I','Nursing','Casual',1),
('KPFH-C025','Ganac','Sheen','S.','Nurse I','Nursing','Casual',1),
('KPFH-C026','Garcia','Juaymah','R.','Nurse I','Nursing','Casual',1),
('KPFH-C027','Glean','Jenelyn De Taza','','Nurse I','Nursing','Casual',1),
('KPFH-C028','Irinco','Geraldine','R.','Nurse I','Nursing','Casual',1),
('KPFH-C029','Jeciel','Jaypee','R.','Nurse I','Nursing','Casual',1),
('KPFH-C030','Limbitco','Louisa May','H.','Nurse I','Nursing','Casual',1),
('KPFH-C031','Madrid','Simon Archival','G.','Nurse I','Nursing','Casual',1),
('KPFH-C032','Malimban','Melba','O.','Nurse I','Nursing','Casual',1),
('KPFH-C033','Marges','Ma. Jamie','V.','Nurse I','Nursing','Casual',1),
('KPFH-C034','Nigoza','Marriah Realiesa Jayd','D.','Nurse I','Nursing','Casual',1),
('KPFH-C035','Orina','Joverlyn','B.','Nurse I','Nursing','Casual',1),
('KPFH-C036','Oriza','Joylene','R.','Nurse I','Nursing','Casual',1),
('KPFH-C037','Penalba','Kimberly','M.','Nurse I','Nursing','Casual',1),
('KPFH-C038','Perez','Jenelyn','A.','Nurse I','Nursing','Casual',1),
('KPFH-C039','Periodico','Aubrey Alliana','T.','Nurse I','Nursing','Casual',1),
('KPFH-C040','Perlado','Arish','R.','Nurse I','Nursing','Casual',1),
('KPFH-C041','Poniente','Jhay-Arr','L.','Nurse I','Nursing','Casual',1),
('KPFH-C042','Robles','Viktor Nigel','F.','Nurse I','Nursing','Casual',1),
('KPFH-C043','Rovillos','Joyce Ann','M.','Nurse I','Nursing','Casual',1),
('KPFH-C044','Sangalang','Mary Justinne','T.','Nurse I','Nursing','Casual',1),
('KPFH-C045','Singson','Louie Glenn','J.','Nurse I','Nursing','Casual',1),
('KPFH-C046','Soriano','Sherlie','S.','Nurse I','Nursing','Casual',1),
('KPFH-C047','Sortijas','Jacqueline','J.','Nurse I','Nursing','Casual',1),
('KPFH-C048','Sortijas','Leo Ray','P.','Nurse I','Nursing','Casual',1),
('KPFH-C049','Sumagui','Liezeth','P.','Nurse I','Nursing','Casual',1),
('KPFH-C050','Talay','Elaiza Mae','L.','Nurse I','Nursing','Casual',1)
,('KPFH-C051','Tandoc','April Rose','D.','Nurse I','Nursing','Casual',1),
('KPFH-C052','Tapawan','Ansherina','A.','Nurse I','Nursing','Casual',1),
('KPFH-C053','Toledo','Kaizen Jay','R.','Nurse I','Nursing','Casual',1),
('KPFH-C054','Tupas','Alpha','M.','Nurse I','Nursing','Casual',1),
('KPFH-C055','Uy','Jasha Asshi','E.','Nurse I','Nursing','Casual',1),
('KPFH-C056','Asas','Monette','V.','Nurse I','Nursing','Casual',1),
('KPFH-C057','Salazar','Sofhia Bianca','B.','Nurse I','Nursing','Casual',1),
-- KPFH Med Tech I
('KPFH-C058','Bataller','Christian Angelo','A.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C059','Briones','Maria Reinalyn','V.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C060','Capillo','Bethel Joy','C.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C061','Creencia','Japie Chester','M.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C062','Libiran','Marie Keicelyn','R.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C063','Liveta','Camella','L.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C064','Poblete','Suzaine','R.','Medical Technologist I','Laboratory','Casual',1),
('KPFH-C065','Ramirez','Michelle','S.','Medical Technologist I','Laboratory','Casual',1),
-- KPFH Pharmacist I
('KPFH-C066','Embudo','April Anne','S.','Pharmacist I','Pharmacy','Casual',1),
('KPFH-C067','Fojas','Gail Allyson','M.','Pharmacist I','Pharmacy','Casual',1),
('KPFH-C068','Mendoza','Luisa','T.','Pharmacist I','Pharmacy','Casual',1),
-- KPFH Radiologic Technologist I
('KPFH-C069','Gan','Valerie','A.','Radiologic Technologist I','Radiology','Casual',1),
('KPFH-C070','Estilloso','Marvy Jay','V.','Radiologic Technologist I','Radiology','Casual',1),
('KPFH-C071','Jose','Resilyn','S.','Radiologic Technologist I','Radiology','Casual',1),
('KPFH-C072','Manuel','Monica','T.','Radiologic Technologist I','Radiology','Casual',1),
('KPFH-C073','Pascua','Marissa','U.','Radiologic Technologist I','Radiology','Casual',1),
('KPFH-C074','Sarmiento','John Rae','R.','Radiologic Technologist I','Radiology','Casual',1),
('KPFH-C075','Bawalan','Jerico Noelle','A.','Radiologic Technologist I','Radiology','Casual',1),
-- KPFH Social Welfare Assistant
('KPFH-C076','Colorado','Rhodora','R.','Social Welfare Assistant','Social Work','Casual',1),
-- KPFH Carpenter
('KPFH-C077','Ortez','Albert Bryan','P.','Administrative Aide IV','Maintenance','Casual',1),
-- KPFH Computer Operators
('KPFH-C078','Lugay','Herbert','C.','Computer Operator II','Administrative','Casual',1),
('KPFH-C079','Bates','July','A.','Computer Operator I','Administrative','Casual',1),
-- KPFH Nursing Attendant I
('KPFH-C080','Abaredes','Malaya','A.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C081','Agner','Analyn','P.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C082','Alviz','Hilda','C.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C083','Ampon','Lalota','O.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C084','Babaan','Ma. Ronnamae','','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C085','Brucal','Rodielyn','M.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C086','Buclatin','Dairiegold','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C087','Dariagan','Chyda','D.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C088','Ersando','Vivian','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C089','Escosia','Lea','D.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C090','Espanola','Asuncion','N.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C091','Isaias','Nenita','R.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C092','Lachica','Marites','U.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C093','Laroa','Patrick','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C094','Leonor','Michellenie','M.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C095','Limare','Kindly','V.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C096','Lubigan','Jasmin','D.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C097','Mabuti','Jerrybel','L.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C098','Manalo','Jaramie','E.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C099','Mangalinao','Khrisha Mhel','L.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C100','Marquez','Charina','C.','Nursing Attendant I','Nursing','Casual',1)
,('KPFH-C101','Matiag','Loida','E.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C102','Mendoza','Melinda','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C103','Oli','Rachel','L.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C104','Parco','Jecelito','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C105','Pocua','Jude','J.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C106','Ramirez','Sherry Rose','N.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C107','Rementas','Celzie Anne','M.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C108','Roguel','Rosemarie','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C109','Romero','Maribel','M.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C110','Saligumba','Jovelyn','S.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C111','Sangalang','Marjorie','O.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C112','Sierra','Ferdinand Nimroh Noah','','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C113','Tan','Quennie','U.','Nursing Attendant I','Nursing','Casual',1),
('KPFH-C114','Vicedo','Marlene','B.','Nursing Attendant I','Nursing','Casual',1),
-- KPFH Admin Aide I
('KPFH-C115','Andam','Lionel Carlo','P.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C116','Asas','Joselito','C.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C117','Aspecto','Rosemarie','R.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C118','Avinante','Russel Bryell','E.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C119','Baclayo','April Joy','G.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C120','Bencito','Christopher','A.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C121','Calitis','Diana','D.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C122','Carza','Ferdinand','C.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C123','Cuesta','Ma. Cristina','V.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C124','Diloy','Gianne','D.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C125','Ersando','Anna Patrisha','N.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C126','Feudo','Carol','F.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C127','Lampadio','Rachelle','R.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C128','Lubigan','Jon Mariner','N.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C129','Pagtalunan','Leonardo Jr.','B.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C130','Penus','Liezel','M.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C131','Poniente','Maricris','L.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C132','Romanes','Rico','C.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C133','Torres','Joseph','G.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C134','Talagtag','Judith','M.','Administrative Aide I','Administrative','Casual',1),
-- KPFH Admin Aide III
('KPFH-C135','Alano','Jennifer','A.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C136','Andion','Amela Remia','V.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C137','Aribal','Raquel','L.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C138','Arzabal','Bernagrace','N.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C139','Badian','Carlo','M.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C140','Bashan','Marjorie','S.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C141','Baylon','Randy','B.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C142','Bermas','Monica','B.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C143','Dela Cruz','Mary Grace','F.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C144','Dumadag','Emmie','I.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C145','Galduen','Reingelbert','Z.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C146','Guevarra','Besinisa','M.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C147','Hondo','Jennilyn','R.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C148','Jeciel','Jonathan','E.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C149','Marasigan','Mae Ann','A.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C150','Padua','Shariel Ann','S.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C151','Penus','Eva','R.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C152','Rala','Lalaine','A.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C153','Ramos','Jerson','J.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C154','Rom','Marineth','V.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C155','Roraldo','Jenievabes','D.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C156','Roxas','Michelle','P.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C157','Sadava','Jesur Jr.','M.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C158','Sallutan','Sherwin','R.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C159','Tongson','Melver Ace','N.','Administrative Aide III','Administrative','Casual',1),
('KPFH-C160','Vivero','Daisy','R.','Administrative Aide III','Administrative','Casual',1),
-- KPFH Lab Aide I
('KPFH-C161','Baldestamon','Gina','D.','Administrative Aide II','Laboratory','Casual',1),
('KPFH-C162','Ignaco','Marry Grace','V.','Administrative Aide II','Laboratory','Casual',1),
-- KPFH Admin Aide I/IW
('KPFH-C163','Antonio','Larvie','H.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C164','Asas','Ayala','M.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C165','Asas','King James R. II','','Administrative Aide I','Administrative','Casual',1),
('KPFH-C166','Cantanero','Darwin','C.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C167','Chavez','Allan','R.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C168','Gabas','Narciso','D.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C169','Jacob','Joseph','P.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C170','Llamado','Gerry','V.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C171','Maligmat','Jonald','Q.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C172','Retutar','Jemeniano','C.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C173','Romero','Radie','M.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C174','Romilla','Richard','A.','Administrative Aide I','Administrative','Casual',1),
('KPFH-C175','Tubid','Alexander','L.','Administrative Aide I','Administrative','Casual',1);

-- ── End of seed data ────────────────────────────────────────────────────────
-- Total: 184 GEAMH + 175 KPFH = 359 casual employees
-- employee_no format: GEAMH-CXXX for GEAMH, KPFH-CXXX for KPFH
